manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    # ▼ 自動計算を無効化するため、urlプロパティで直接GitHubのアドレスを指定します
    - name: zmk-locales
      url: https://github.com
      revision: main
  self:
    path: config
